theme: jekyll-theme-minimal
title: Calf Raise homepage
description: Calf Raise is the first scientifically designed app to measure Calf Raise performance from videos using your iPad or iPhone. With an innovative design and validated tracking algorithms, Calf Raise brings science to your practice!
logo: /images/logo.png
